spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      authentication-database: admin
  main:
    banner-mode: off

  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB

